#include <iostream>

int main()
{

    /*
    // std::nothrow : tell that don't throw an exception when the operations fails
    // it return null so we can check 
    int* ptr {new(std::nothrow) int[1000000000000000]};

    if(ptr == nullptr)
    {
        // that mean the operation will throw an exceptions so didn't be executed
        std::cout << " the new failed !!! "<<std::endl;
    }
    else 
    {
        std::cout << " the program ends well "<<std::endl;
    }
    */

   /*
   // exception mechanism
   try
   {
    int* ptr {new int[1000000000000000]}; // Code that might throw an exception
   }
   catch(const std::exception& e) // catch the exception reason
   {
    std::cout << e.what() << std::endl;
   }
   */
   




    return 0;

}